name: booking_desktop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  go_router: ^14.6.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  
  shared_preferences: ^2.3.2
  flutter_map_marker_cluster: ^1.3.5
  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  printing: ^5.13.0
  intl: ^0.19.0
  flutter_polyline_points: ^2.0.0
  http: ^1.2.0
  webview_flutter: ^4.7.0
  file_picker: ^6.1.1
  syncfusion_flutter_pdf: ^24.1.41

flutter_icons:
  android: true
  ios: true

  macos:
    generate: true

  windows:
    generate: true

  image_path: "assets/icon/TourFlowIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/pdf/logos/CSSLogo.png
    - assets/pdf/logos/Starcoachlogo.png
    - assets/pdf/logos/LOGOapp.png
    - assets/pdf/buses/12_sleeper.png
    - assets/pdf/buses/14_sleeper.png
    - assets/pdf/buses/16_sleeper.png
    - assets/pdf/buses/18_sleeper.png
    - assets/pdf/buses/DDBus.png
    - assets/pdf/buses/DDBuskart.png
    - assets/pdf/template_page0.png
    - assets/pdf/logos/TourFlowLogo.png
    - assets/fonts/Calibri.ttf
    - assets/fonts/Calibrib.ttf