name: booking_desktop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.2
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.1.0
  file_picker: ^8.1.2
  shared_preferences: ^2.3.2

  cupertino_icons: ^1.0.8
  pdf: ^3.11.0
  printing: ^5.13.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/pdf/logos/CSSLogo.png
    - assets/pdf/logos/Starcoachlogo.png
    - assets/pdf/buses/12_sleeper.png
    - assets/pdf/buses/14_sleeper.png
    - assets/pdf/buses/16_sleeper.png
    - assets/pdf/buses/18_sleeper.png
    - assets/pdf/template_page0.png